Repository Nexters/mashow-iOS, pull requests merged in 2024-07, with the labels that each got.

#2 [chore][#1] Tuist integrate
  .gitignore
  .mise.toml
  Mashow.entitlements
  Plugins/Mashow/Package.swift
  Plugins/Mashow/Plugin.swift
  Plugins/Mashow/ProjectDescriptionHelpers/LocalHelper.swift
  Plugins/Mashow/Sources/tuist-my-cli/main.swift
  Project.swift
  Targets/Mashow/Resources/LaunchScreen.storyboard
  Targets/Mashow/Sources/Application/AppDelegate.swift
  Targets/Mashow/Sources/Application/SceneDelegate.swift
  Targets/Mashow/Sources/MashowRootViewController.swift
  Targets/Mashow/Tests/AppTests.swift
  Targets/MashowIOS/Sources/AppDelegate.swift
  Targets/MashowKit/Sources/MashowKit.swift
  Targets/MashowKit/Tests/MashowKitTests.swift
  Targets/MashowUI/Sources/MashowUI.swift
  Targets/MashowUI/Tests/MashowUITests.swift
  Tuist/Config.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/Signing/Mashow.Debug.mobileprovision
  Tuist/Signing/Mashow.Release.mobileprovision
  Tuist/Signing/ios_development.cer.encrypted
  Tuist/Signing/ios_development.p12.encrypted
  Tuist/Signing/ios_distribution.cer.encrypted
  Tuist/Signing/ios_distribution.p12.encrypted
  setup.sh
Labels: 🧹 chore

#5 [feat][#4] UIKit 컴포넌트 live preview 만들기
  Targets/Mashow/Sources/MashowRootViewController.swift
  Targets/Mashow/Sources/Util/UIView+Preview.swift
  Targets/Mashow/Sources/Util/UIViewController+Preview.swift
Labels: ⚡️ improve

#9 [feat][#3] 네트워크 레이어 세팅 & Environment 객체 추가
  Targets/Mashow/Sources/Util/Environment.swift
  Targets/Mashow/Sources/Util/Network/API.swift
  Targets/Mashow/Sources/Util/Network/NetworkManager.swift
  Targets/Mashow/Sources/Util/View/UIView+Preview.swift
  Targets/Mashow/Sources/Util/View/UIViewController+Preview.swift
  Targets/Mashow/Tests/Util/NetworkMangerTests.swift
  Tuist/Dependencies.swift
Labels: 🧹 chore

#10 [feat][#7] 카카오 로그인 & `AuthManager` & `Storage` & `XCConfig` etc.
  .gitignore
  Configurations/.gitkeep
  Targets/Mashow/Sources/Application/AppDelegate.swift
  Targets/Mashow/Sources/Util/Environment.swift
  Targets/Mashow/Sources/Util/Login/AuthorizationManager+Apple.swift
  Targets/Mashow/Sources/Util/Login/AuthorizationManager+Kakao.swift
  Targets/Mashow/Sources/Util/Login/AuthorizationManager.swift
  Targets/Mashow/Sources/Util/Network/API.swift
  Targets/Mashow/Sources/Util/Network/NetworkManager.swift
  Targets/Mashow/Sources/Util/Storage/StorageManager.swift
  Targets/Mashow/Tests/Util/NetworkMangerTests.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: ⚡️ improve

#11 [feat][#8] 애플로그인 구현
  Targets/Mashow/Sources/MashowRootViewController.swift
  Targets/Mashow/Sources/Util/Login/AuthorizationManager+Apple.swift
  Targets/Mashow/Sources/Util/Login/AuthorizationManager.swift
Labels: ✨ feature
